### ISSUE TITLE
Unable to dump to fs properly a ZIM file

### ISSUE THREAD

**Issue by kelson42** [openzim/zim-tools#200] opened 2020-12-11 11:54 UTC
```
$ zimdump dump --dir=4242 wiki.openzim.org_en_all_2020-12.zim 
Exception: Error creating symlink from A/wiki.openzim.org/w/images/favicon.ico to 4242/-//favicon
$
```

Here is the ZIM file:
[wiki.openzim.org_en_all_2020-12.zim.zip](https://github.com/openzim/zim-tools/files/5678965/wiki.openzim.org_en_all_2020-12.zim.zip)

**Comment by maneeshpm** [comment] 2021-01-05 20:03
Hey again @kelson42! if this issue is still up for grabs, I would like to work on it. I was able to reproduce the error, seems like a symlink path error. Can you provide some pointers on how to approach this issue if possible?

**Comment by kelson42** [comment] 2021-01-05 20:06
@maneeshpm Yes feel free. Unfortunaty I can not really help you but make search in the closed tickets and PR, this will probably be helpful. Fell free to ask as well if you have a question about how the zimdump should behave.

**Comment by maneeshpm** [comment] 2021-01-05 20:13
Thanks @kelson42, that would be awesome. Meanwhile I can try to pinpoint the exact error.

**Comment by kelson42** [comment] 2021-01-06 10:09
@maneeshpm This search in the issues/PRs is a work for you, I don't plan to do anything.

**Comment by maneeshpm** [comment] 2021-01-06 12:48
The exception is generating an `errno 2 ENOENT`. This is caused by the following issues:
- On printing out the path components, for the favicon.ico
`filename: /favicon, directory: 4242, separator: /, retative_path: -//favicon` 
the file name contains a preceding '/', fixed by making `filename = path.substr(position+1);` on line 312. Upon doing this, a valid file path `4242/-/favicon` can be generated.
- Stuck again at the '-' of file path. The `createdir()` function ignores it since `path.size()<=1` and returns. So the directory '-' is never created and hence the ENOENT error.

I guess this might be the issue. After manually creating the '-' directory, things were somewhat different
```
$  zimdump dump --dir=4242 wiki.openzim.org_en_all_2020-12.zim.zip \
Wrote 4242/A/404.html to 4242/_exceptions/A%2f404.html
Wrote 4242/A/index.html to 4242/_exceptions/A%2findex.html
Wrote 4242/A/load.js to 4242/_exceptions/A%2fload.js
Wrote 4242/A/sw.js to 4242/_exceptions/A%2fsw.js
Wrote 4242/A/topFrame.html to 4242/_exceptions/A%2ftopFrame.html
Error writing file to errors dir. 4242/_exceptions/A%2fwiki.openzim.org%2fw%2fload.php?debug=false&lang=en&modules=ext.eventLogging.subscriber%7Cext.visualEditor.desktopArticleTarget.init%7Cext.visualEditor.supportCheck%2CtargetLoader%2CtempWikitextEditorWidget%2Ctrack%2Cve%7Cjquery.accessKeyLabel%2CcheckboxShiftClick%2Cclient%2C~1
Exception: Error writing file to errors dir. 4242/_exceptions/A%2fwiki.openzim.org%2fw%2fload.php?debug=false&lang=en&modules=ext.eventLogging.subscriber%7Cext.visualEditor.desktopArticleTarget.init%7Cext.visualEditor.supportCheck%2CtargetLoader%2CtempWikitextEditorWidget%2Ctrack%2Cve%7Cjquery.accessKeyLabel%2CcheckboxShiftClick%2Cclient%2C~1
```
@kelson42 Is this the actual expected behavior?

**Comment by kelson42** [comment] 2021-01-07 11:57
@maneeshpm It is not the proper behaviour, otherwise why should I have open a ticket?!

**Comment by kelson42** [comment] 2021-01-07 12:05
@maneeshpm I don't really understand your technical explanation. But that does not matter for the moment? Do you understand where is the bug? How to fix it?

BTW, the message is wrong:
```
Exception: Error creating symlink from A/wiki.openzim.org/w/images/favicon.ico to 4242/-//favicon
```

The symlink is the otherway around from `-/favicon` to `A/wiki.openzim.org/w/images/favicon.ico`.

**Comment by kelson42** [comment] 2021-01-07 12:14
@maneeshpm I believe, you need to fix the function `createDir()`. I don't understand at all why we have:
```
if (path.size() <= 1)
        return ;
```

**Comment by kelson42** [comment] 2021-01-07 12:42
@maneeshpm Many things are wrong here. Just remark, that the input `--dir=` value is not even checked/sanitized properly. As a consequence, you don't even know if there is a trailing slash or not. Please start with this.

**Comment by maneeshpm** [comment] 2021-01-07 12:58
@kelson42 Yeah, that's what I tried to convey through the second point. Verifying if the input `--dir=<path>` is managed properly and checking if the creation of directories is taking place as expected looks like the right place to start. I am working on it, will keep you posted.

**Comment by maneeshpm** [comment] 2021-01-07 13:51
@kelson42 I have fixed some lines and the command is not crashing anymore, it prints the following:
```
$ zimdump dump --dir=4242 wiki.openzim.org_en_all_2020-12.zim.zip 
Wrote 4242/A/wiki.openzim.org/wiki/ZIM_File_Format/4 to 4242/_exceptions/A%2fwiki.openzim.org%2fwiki%2fZIM_File_Format%2f4
Wrote 4242/H/wiki.openzim.org/wiki/ZIM_File_Format/4 to 4242/_exceptions/H%2fwiki.openzim.org%2fwiki%2fZIM_File_Format%2f4
```
And writes the following to the file system:
```
$ tree -L 2                                                                
4242
├── -
│   └── favicon -> A/wiki.openzim.org/w/images/favicon.ico
├── A
│   ├── 404.html
│   ├── commons.wikimedia.org
│   ├── d1iczxrky3cnb2.cloudfront.net
│   ├── index.html
│   ├── load.js
│   ├── stats.kiwix.org
│   ├── sw.js
│   ├── topFrame.html
│   ├── update.googleapis.com
│   ├── upload.wikimedia.org
│   └── wiki.openzim.org
├── _exceptions
│   ├── A%2fwiki.openzim.org%2fwiki%2fZIM_File_Format%2f4
│   └── H%2fwiki.openzim.org%2fwiki%2fZIM_File_Format%2f4
├── H
│   ├── commons.wikimedia.org
│   ├── d1iczxrky3cnb2.cloudfront.net
│   ├── stats.kiwix.org
│   ├── update.googleapis.com
│   ├── upload.wikimedia.org
│   └── wiki.openzim.org
├── M
│   ├── Compression
│   ├── Counter
│   ├── Creator
│   ├── Date
│   ├── Description
│   ├── Language
│   ├── Name
│   ├── Publisher
│   ├── Scraper
│   ├── Source
│   ├── Tags
│   └── Title
└── X
    ├── fulltext
    └── title

20 directories, 20 files
```
Is this the expected behavior?

**Comment by kelson42** [comment] 2021-01-07 14:02
@maneeshpm I would say that it looks better yes :) Please open a PR.

**Closed** 2021-01-09 18:04 UTC
Labels: bug, good first issue, zimdump
