### ISSUE TITLE
zimdump - Bypassing excessively long filenames.

### ISSUE THREAD

**Issue by ISJ-439** [openzim/zim-tools#318] opened 2022-08-23 06:21 UTC
Hello,

The filenames in a zim im trying to recover are too long, is it possible to add a flag or similar to bypass this or truncate it?

The error is "Exception: Error writing file to errors dir. " with an excessively long file name following. 

Thanks

**Comment by mgautierfr** [comment] 2022-08-23 09:47
It should already be the case, we truncate filename longer than 255 chars.
What is the file name you want to extract ?
Which command are you using ?

**Comment by ISJ-439** [comment] 2022-08-23 14:22
Im going to replace the site details with an equal number of x's for privacy, hope that's okay.

ZIMtools Version: **3.1.1-2**

Command
**/home/localadmin/Downloads/zim-tools_linux-x86_64-3.1.1-2/zimdump  dump --dir='/mnt/2TB' ./xxxxxxxxxxxxx.com-May2022_2022-05.zim**

Filename
Wrote /mnt/2TB/H/xxxxxxxxxxxxx.com/category/xxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxx/page/43/ to /mnt/2TB/_exceptions/H%2fxxxxxxxxxxxxx.com%2fxxxxxxxx%2fxxxxxxxxxxxxxxxxx%2fxxxxxxxxxxxxxxx%2fpage%2f43%2f
Wrote /mnt/2TB/H/www.bitchute.com/embed/xxxxxxxxxxx/view/ to /mnt/2TB/_exceptions/H%2fwww.bitchute.com%2fembed%xxxxxxxxxxx%2fview%2f
Error writing file to errors dir. **/mnt/2TB/_exceptions/A%2fhtml5-player.libsyn.com%2fembed%2fepisode%2xxx%2xxxxxxxx%2fheight%2f90%2fwidth%2f640%2ftheme%2fcustom%2fautonext%2fno%2fthumbnail%2fyes%2fautoplay%2fno%2fpreload%2fno%2fno_addthis%2fno%2fdirection%2fbackward%2frender-playlist%2fno%2fcustom-color%2f0009aa%2f**
Exception: Error writing file to errors dir. **/mnt/2TB/_exceptions/A%2fhtml5-player.libsyn.com%2fembed%2fepisode%2xxx%2xxxxxxxx%2fheight%2f90%2fwidth%2f640%2ftheme%2fcustom%2fautonext%2fno%2fthumbnail%2fyes%2fautoplay%2fno%2fpreload%2fno%2fno_addthis%2fno%2fdirection%2fbackward%2frender-playlist%2fno%2fcustom-color%2f0009aa%2f**

{end of program output}

**Comment by ISJ-439** [comment] 2022-08-23 14:23
This is 262 characters which is over the 255 limit for file names.

**Comment by mgautierfr** [comment] 2022-08-30 16:08
What is failing is the writing of errored file.

zim dump try to write the file in your out directory (`/mnt/2TB`) but if it fails for some reason, it will write the file in the exception directory (`/mnt/2TB/_exceptions`), when doing so, it replace all `/` by `%2f` (so there is no subdirectory) and it doesn't try to truncate the filename.

The question is why it fails to write the file in the first instance ? (Sadly, zimdump doesn't report the error information)
- What is the content of `mnt/2TB/A/html5-player.libsyn.com/embed/episode/xx/xxxxxxx/height/90/width/640/theme/custom/autonext/no/thumbnail/yes/autoplay/no/preload/no/no_addthis/no/direction/backward/render-playlist/no/custom-color/0009aa/` ?
- Is your directory full ? Or with some quota ?
- ...

**Comment by ISJ-439** [comment] 2022-09-01 20:20
Hello sir,

Firstly, thank you for your time.

"What is the content of mnt/2T"
The content is likely related to a MP3 player applet, yes I know this is not supported and im sorry to use this outside the scope.

"Is your directory full ? Or with some quota ?" 
First thing i checked, no sir, almost a TB free, is set the directory to 'chmod -R ./* 777' so its not permissions.

**My purposed solution:** Provide a switch to bypass errors and just continue extracting. This would likely be simple and easy, in my limited knowledge.

Thank you.

**Comment by mgautierfr** [comment] 2022-09-02 08:09
I agree with you proposal.
But it would even be better to also know why it fails. If you can provide me the zim file (even privatly if you don't what to publish it), I could investigate what is the root cause and fix it.

**Comment by kelson42** [comment] 2022-09-02 09:49
No way to build anyt

> **My purposed solution:** Provide a switch to bypass errors and just continue extracting. This would likely be simple and easy, in my limited knowledge.

We should first 100% understand the root cause.

**Comment by LTVA1** [comment] 2022-12-02 17:18
Also having this issue, can provide a zim file for tests. Although it is around 3 GB in size, not sure where to upload it

**Comment by mgautierfr** [comment] 2022-12-07 16:07
You can use any file share service, for exemple wetransfer.com or file.io 
They are limited to 2GB files but you can cut the zim file.

**Comment by LTVA1** [comment] 2022-12-07 16:18
I will try to limit crawl scope so the file would be less than 2 gb in size asap

**Comment by benoit74** [comment] 2023-11-01 09:06
Sample file for tests: https://www.swisstransfer.com/d/306ae305-8b17-455f-862f-13c15ca93121

**Comment by kelson42** [comment] 2024-03-31 20:15
This is basically a duplicate of #213

**Closed by kelson42** 2024-03-31 20:15 UTC
Labels: bug, question, zimdump
