### ISSUE TITLE
Rewrite API of zimdump.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/zim-tools#70] opened 2020-01-14 15:01 UTC
Zimdump is a pretty old tool. It was mainly used a debug tools. Its API is very odd and performance is the last of this feature.

There is a lot of issue about zimdump. Some about the odd API (#63, #4), some about using zimdump as a "real" tool and not just a debug tool (#69, #24, #68).
In both case, we should rethink the API of the tool.

There are different actions done by zimdump :
- Print zim file info (the zim header)
- Print content of an article
- Print info about an article (the dirent)
- List the content of a zim file
- Dump all articles (or a subset) in a directory
- Verify the checksum of the zim file.

I propose a API based on subcommand.
- dump
- list
- info

`dump` subcommand would be used to dump the content of article(s). Either on stdout (for one article) or in a directory (for one or several articles).

`list` would be use to list all (or a subset ?) articles (url or title). It could be use to check than a article exists.

`info` would be use to print info on the zim file or on a specific article.

The "verify checksum action" should be in `zimcheck` and will be removed from `zimdump`.

Articles could be selected by Id, Url or Title. Url would have to be "long url" (with namespace).

Some command line examples (exact option's names are not definitive) :
`zimdump <zim_file> info` Print the header of the zimfile.
`zimdump <zim_file> info --id 50` Print dirent of article 50
`zimdump <zim_file> info --url A/foo.html` Print dirent of article 'A/foo.html' (or 'foo.html' in namespace 'A')
`zimdump <zim_file> info --title Foo` Print dirent of article named "Foo"
`zimdump <zim_file> list` List all article (url) in the zim file.
`zimdump <zim_file> list --title` List all article (title) in the zim file.
`zimdump <zim_file> dump --output Foo` Dump all articles in the directory `Foo`.
`zimdump <zim_file> dump --title Foo --output Foo.html` Dump the content of the artcle named "Foo" in Foo.html.
`zimdump <zim_file> dump --url A/foo.html --output Foo.html` Dump the content of the article `A/foo.html` in Foo.html.
`zimdump <zim_file> dump --url A/foo.html --output -` Dump the content of the article `A/foo.html` on stdout.

**Comment by kelson42** [comment] 2020-05-22 08:10
@mgautierfr @MiguelRocha To me this is how it should looks like:
``` 
usage: zimdump <command> [<args>] <file>

These are common zimdump commands used in various situations:

    ls            List content
    dump          Dump content
        --dir     Write content to the filesystem (terminal otherwise)
    info          Show meta structure details

 Filters:
    <ls> and <dump> commands accept as <args>:
        --idx     Content index
        --ns      Content namespace (default 'A')
        --url     Content url

Options:
    -h, --help    Show this help
    --version     Show zimdump version
```

It is a lot simplier that what we ever had before but should do the job. I don't think I have forgotten something important. Le me know if I have or if something is unclear.

**Comment by mgautierfr** [comment] 2020-05-25 08:54
Here few remarks, I don't know if it is intended or not :

- It would be not possible to search for an article by title. 
- `info` was used to print "medatada" about a specific article. We should be able to use filters with it.
- What is `ls` command output ? Url, Title, "table" ?
- Does filter are "exact match" or we can use wilcards ? It would be pretty difficult to implement wilcard efficiently but maybe we want to allow filtering using a prefix.

I think the `dump` command is a bit more complex that we think at first. If we dump articles (with filter or not), the obvious only output is a directory. But if we dump only one article, the output could be a filename or the terminal. We could simplify with directory or terminal only, but the API should reflect this behavior difference.

**Comment by kelson42** [comment] 2020-05-25 09:38
>     * It would be not possible to search for an article by title.

Yes, I never use this and this is to me somewhoe a duplicate of `zimsearch` and `kiwix-search`. That said if someone really needs it... we can keep it.
 
>     * `info` was used to print "medatada" about a specific article. We should be able to use filters with it.

This is what `list` should do. `list` without printing details (but not content) about the articles does not really make sense IMO.
 
>     * What is `ls` command output ? Url, Title, "table" ?

Everything necessary. This is like `-i -l` for the current one.

>     * Does filter are "exact match" or we can use wilcards ? It would be pretty difficult to implement wilcard efficiently but maybe we want to allow filtering using a prefix.

It should be exact match (I guess you mean for the url filter).

> I think the `dump` command is a bit more complex that we think at first. If we dump articles (with filter or not), the obvious only output is a directory. But if we dump only one article, the output could be a filename or the terminal. We could simplify with directory or terminal only, but the API should reflect this behavior difference.

`dump` is indeed the tricky one. Writing to the fs seems "obvious" only if you consider having many results to the fitler. Otherwise printing to STDOUT is obvious. Because I believe the that the second scenario is the most obvious then we will print per default all the articles in STDOUT.

**Comment by mgautierfr** [comment] 2020-05-25 12:00
> This is what list should do. list without printing details (but not content) about the articles does not really make sense IMO.

> Everything necessary. This is like -i -l for the current one.

I have used `list` to list the articles in a zim file and then use info to have information about a specific article.
I am not again using `list` to have information about an article but it would be nice to keep the feature to list the article in a zim file (filtering is not necessary here, you can use grep/less/... to do it).

I realize that with https://github.com/openzim/libzim/issues/325, the metadata are not considered anymore as article (they are stored as article but it is a implementation detail, they are not "logical" articles"). I think that they should be displayed using `info` and not dumped with `dump`. (I'm not sure they should be listed with `list`).

> It should be exact match (I guess you mean for the url filter).

Yes, for url (and potentially title, but we remove it).
I wonder what is the usage of `--namespace` if we do exact matching. Should it be used with `--url` ? If it is always used with url, maybe we can remove it and make the url contains the namespace (longUrl). We should also think about it within the openzim/libzim#325 perspective.

> dump is indeed the tricky one...

If filter are exact match, `dump` behaves pretty simple : if there is a filter, dump to stdout. Else dump articles in a directory.
It means that dump take only one option : either a filter or `--dir`.

**Comment by kelson42** [comment] 2020-05-25 12:25
> > This is what list should do. list without printing details (but not content) about the articles does not really make sense IMO.
> 
> > Everything necessary. This is like -i -l for the current one.
> 
> I have used `list` to list the articles in a zim file and then use `info` to have information about a specific article.
> I am not again using `list` to have information about an article but it would be nice to keep the feature to list the article in a zim file (filtering is not necessary here, you can use grep/less/... to do it).

I understand what you mean. Maybe we could print only the URL (+namespace?) per default and keep `--metadata` to print other details ?

> I realize that with [openzim/libzim#325](https://github.com/openzim/libzim/issues/325), the metadata are not considered anymore as article (they are stored as article but it is a implementation detail, they are not "logical" articles"). I think that they should be displayed using `info` and not dumped with `dump`. (I'm not sure they should be listed with `list`).

Even if this is important to keep that point in mind, I would prefer not to talk about that now (the problem is complex enough and I don't think this something wee need absolutely to talk about now). One important thing about the "dump" action: depending which namespace is given in the filter, the content of any (or all?) namespace might be dumped.

> > It should be exact match (I guess you mean for the url filter).
> 
> Yes, for url (and potentially title, but we remove it).
> I wonder what is the usage of `--namespace` if we do exact matching. Should it be used with `--url` ? If it is always used with url, maybe we can remove it and make the url contains the namespace (longUrl). We should also think about it within the [openzim/libzim#325](https://github.com/openzim/libzim/issues/325) perspective.

To find a specific content, we will have to use `--url` and `--namespace` together. Or do we want to have a default filter on the main namespace? I'm not so sure we should advocate/keep the concept of longURL here, I find it confusing (I don't understand as well how to really make the difference if with have `/A/foobar` to know if we talk about `A` namespace or a URL `A/foobar` in the main/transparent namespace).

> > dump is indeed the tricky one...
> 
> If filter are exact match, `dump` behaves pretty simple : if there is a filter, dump to stdout. Else dump articles in a directory.
> It means that dump take only one option : either a filter or `--dir`.

I don't think this is a proper way because then you won't be able to dump only the content of one namespace to the disk. I prefer how I have proposed it.

**Comment by mgautierfr** [comment] 2020-05-25 13:22
> Maybe we could print only the URL (+namespace?) per default and keep --metadata to print other details ?

Yes, seems good.

>  I don't think this is a proper way because then you won't be able to dump only the content of one namespace to the disk. I prefer how I have proposed it.

I miss the use case of dumping a specific namespace. The "exact match" dupe me. So `--dir` and --namespace` together are valid.
But what is the behavior of `zimdump dump --dir mydir --url foo.htm zimfile` ?

> I don't understand as well how to really make the difference if we have /A/foobar between A namespace or a URL A/foobar in the main/transparent namespace

That a good question, and I don't have the answer :)
Let's keep the `--namespace` and `--url` (short url). When we will move to openzim/libzim#235, it will be simpler to just drop the `--namespace` option.

**Comment by kelson42** [comment] 2020-06-01 05:13
After discussion with @mgautierfr we came to this:

``` 
usage: zimdump <command> [<args>] <file>

These are common zimdump commands used in various situations:

    ls            List content
        --details With details
    dump          Dump content
        --dir     Write content to the filesystem (terminal otherwise)
    info          Show meta structure details

 Filters:
    <ls> and <dump> commands accept as <args>:
        --idx     Content index
        --url     Content url
        --ns     Namespace

Options:
    -h, --help    Show this help
    --version     Show zimdump version
```

So we always work on the content namespaces per default, ie (A, I, -) for the moment and only one in the future. `ls` prints only (short) URL per default, all the details with `--details`.

**Comment by mgautierfr** [comment] 2020-06-01 10:36
As we use docopt and this force a standard help message, the help message should be :
```
Usage:
  zimdump ls|list [--details] [--idx=INDEX|([--url=URL] [--ns=N])] [--] <file>
  zimdump dump --dir=DIR [--ns=N] [--] <file>
  zimdump dump (--idx=INDEX|(--url=URL [--ns=N])) [--] <file>
  zimdump info [--] <file>
  zimdump -h | --help
  zimdump --version

Selectors:
  --idx INDEX  The index of the article to list/dump.
  --url URL    The url of the article to list/dump
  --ns N       The namespace of the article(s) to list/dump.
               When used with `--url`, default to `A`.
               If no `--url` is provided (for  `zimdump dump`) default to "no filter".

Options:
  --details    Show details about the articles. Else, list only the url of the article(s).
  --dir=DIR    Directory where to dump the article(s) content.
  -h, --help   Show this help
  --version    Show zimdump version.

Return value:
  0 : If no error
  1 : If no (or more than 1) articles correspond to the selectors.
  2 : If an error/warning has been issue during the dump.
      See DIR/dump_errors.log for the listing of the errors.
```

I add :
- the command `list` as a alias to `ls`
- the return value.

I've also separate the case where we dump several articles (and so we need the option `--dir`) from where we dump the content of only one article (and so we dump on standard output).

I hope we all agree now.

**Comment by MiguelRocha** [comment] 2020-06-03 10:06
@mgautierfr @kelson42 thanks for the requirements. 

If I understand correctly the details are used for printing metainfo about the article such as title, idx, type etc. In the old version we also have "extra" which is used to print parameter information about the article. Should we maintain this option or drop it?

**Comment by mgautierfr** [comment] 2020-06-03 10:08
The old `extra` is replaced by `details`.

**Closed** 2020-07-08 14:52 UTC
Labels: IPFS, enhancement, zimdump
