### ISSUE TITLE
zimdump doesn't report missing articles

### ISSUE THREAD

**Issue by rgaudin** [openzim/zim-tools#63] opened 2019-08-14 19:23 UTC
It seems like a reasonable behavior to expect that `-u` raise an error if the requested URL is not found.

I understand how `-f` can be more flexible but without a strict `-u`, there's no easy way to check for the content/existence of an URL
```
  -f title  find article
  -u url    find article by url
```

ATM, the behavior is to send the next article.

**Comment by kelson42** [comment] 2020-06-09 12:28
@MiguelRocha I think as well that this should be fixed with the rewritting you are doing. Please let me know if not.

**Comment by kelson42** [comment] 2020-06-12 10:36
> Then your breaking the API. But I think this discussion is not relevant. We already plan to change the API ([openzim/libzim#345](https://github.com/openzim/libzim/issues/345)), we should delay this issue to use the new API.

Good to me if the problem is fixed in the next months anyway. Thank you both for your feedback.

**Comment by mgautierfr** [comment] 2020-07-09 13:36
This should be fixed with the last PR of @MiguelRocha #89

**Closed by mgautierfr** 2020-07-09 13:36 UTC
Labels: bug, zimdump
